pam-unauthorized-module="""
The package installs a PAM module. If the package is intended for inclusion in any SUSE product please open a bug report to request review of the package by the security team. Please refer to #AUDIT_BUG_URL# for more information.
"""
pam-ghost-module="""
The package installs a PAM module as %ghost file. This is not allowed, since it is impossible to review. Please refer to #AUDIT_BUG_URL# for more information.
"""
