[[WorldWritableWhitelist]]
package = "filesystem"
bug = "bsc#1174642"
note = "Public standard sticky-bit directories"
files = [
  {
    path = '/tmp',
    mode = "drwxrwxrwt",
    owner = "root",
    group = "root"
  },
  {
    path = '/var/tmp',
    mode = "drwxrwxrwt",
    owner = "root",
    group = "root"
  },
  {
    path = '/var/spool/mail',
    mode = "drwxrwxrwt",
    owner = "root",
    group = "root"
  },
  {
    path = '/tmp/.X11-unix',
    mode = "drwxrwxrwt",
    owner = "root",
    group = "root"
  },
  {
    path = '/tmp/.ICE-unix',
    mode = "drwxrwxrwt",
    owner = "root",
    group = "root"
  }
]

[[WorldWritableWhitelist]]
package = "nscd"
bug = "bsc#1174642"
note = "nss caching daemon socket. is packaged as %ghost, therefore 'appears' to be a regular file."
files = [
  {
    path = '/run/nscd/socket',
    mode = "-rw-rw-rw-",
    owner = "root",
    group = "root"
  }
]
